language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
branches:
  only: src
install:
- pip install --upgrade pip setuptools wheel
- pip install --upgrade git+https://github.com/lektor/lektor.git@master#egg=Lektor
script: "lektor build"
deploy:
  provider: script
  script: lektor deploy ghpages
